CREATE TABLE recipes (
    id              INT PRIMARY KEY AUTO_INCREMENT,
    rcp_seq         VARCHAR(10) UNIQUE NOT NULL,
    name            VARCHAR(200) NOT NULL,
    category        VARCHAR(50),
    cooking_method  VARCHAR(50),
    calories        FLOAT,
    protein         FLOAT,
    fat             FLOAT,
    sodium          FLOAT,
    carbs           FLOAT,
    cooking_time      INT,
    difficulty        TINYINT,
    spicy_level       TINYINT,
    ingredient_count  INT,
    meal_type_tags    JSON,
    summary                TEXT,
    taste_tags             JSON,
    texture_tags           JSON,
    recommended_situations JSON,
    main_ingredients       JSON,
    enrichment_flags       JSON,
    ingredients   TEXT,
    manuals_text  TEXT,
    img_main      VARCHAR(500),
    img_thumb     VARCHAR(500),
    enrichment_model VARCHAR(100),
    enriched_at      DATETIME,
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
